apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-a0br
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-a0br
    app.kubernetes.io/part-of: tkrw-pr712-0075-0022-app
  name: devfile-sample-a0br
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-a0br
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-a0br
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-a0br@sha256:fc7e956e9b5f47f4fea5699c8f07d7d43f239b38d14121157feab6e80d521415
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
